base/urls.py
from django.contrib import admin
from django.urls import path,include
import base.views as views

app_name='base'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<int:id>', views.profile, name='profile'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('authenticate/', views.authenticate_view, name='authenticate'),
    path('detail/<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('raw/<int:id>/', views.raw, name='raw'),
    path('logout/', views.logout_view, name='logout'),
    path('download/<int:id>', views.download_view, name='download'),
    path('search/',views.search, name='search'),
    path('delete/<int:id>',views.delete, name='delete'),
    path('change-mode/',views.change_mode, name='change_mode'),
    path('back/',views.back, name='back'),
]

openpaste_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Message(models.Model):
    title = models.CharField(max_length=50, null=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    body = models.TextField(null=False)
    id = models.AutoField(primary_key=True, null=False, unique=True)
    views = models.IntegerField(default=0, null=False)
    public = models.BooleanField(default=True, null=False)

    def __str__(self):
        return self.title[:50]

base/views.py
from django.shortcuts import render,redirect, reverse
from django.http import HttpResponse,HttpResponseRedirect
# Create your views here.
from base.models import Message
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from slugify import slugify
from django.db.models import Q
import git

def get_page(request):
    if not 'page' in request.GET:
        return 1
    else:
        return int(request.GET['page'])

def get_page_max(messages_count):
    page_max = messages_count // 10
   
    page_max+= 1 if not messages_count % 10 == 0 else 0
    if(page_max==0):
        page_max+=1
    return page_max

def get_mode(request):
    if 'mode' in request.session:
        return request.session['mode']
    else:
        return 'light'

def index(request):
    repo = git.Repo(search_parent_directories=True)
    sha = repo.head.object.hexsha
    recent_messages = Message.objects.filter(public=True).order_by('-created_at')[:10]
    message = Message()
    message.public =True
    
    context = {
        "recent_messages":recent_messages,
        "sha":sha,
        "message":message,
        "mode":get_mode(request),
        
    }
    return render(request, 'base/index.html',context)

def profile(request,id):
    user = User.objects.get(id=id)

    page = get_page(request)
    all_messages_count = Message.objects.filter(owner=user).count()
    
    page_max = get_page_max(all_messages_count)
    
    if request.user == user:
        messages = Message.objects.filter(owner=user).order_by('-created_at')[(page-1)*10:(page)*10]
    else:
        messages = Message.objects.filter(owner=user, public=True).order_by('-created_at')[(page-1)*10:(page)*10]
    
    recent_messages = Message.objects.filter(public=True).order_by('-created_at')[:10]
    show_page_selector = not((page-1 == 0) and (page_max == page)) 
    
    context = {
        "messages":messages,
        "recent_messages":recent_messages,
        "user":user,
        "page_prev":page-1,
        "page_next":page+1,
        "page_max":page_max,
        "page":page,
        "show_page_selector":show_page_selector,
        "mode":get_mode(request),
        
    }
    return render(request, 'base/profile.html',context)
    
def login_view(request):
    
    if 'error_msg' in request.session:
        error_msg = request.session['error_msg']
        request.session['error_msg'] = None
    else:
       error_msg = None 
    context = {
        'error_msg':error_msg,
        "mode":get_mode(request),
    }
    return render(request, 'base/login.html',context)
    

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        request.session['username']=username
        password = request.POST['password']
        if User.objects.filter(username=username).exists():
            request.session['error_msg']='The user already exists'
            return redirect('base:register')
        if len(password)<7:
            request.session['error_msg']='Please use a password 8 characters or longer'
            return redirect('base:register')
        
        user = User.objects.create_user(username=username,password=password)
        user.save()
        login(request, user)
        return redirect('base:profile',user.id)
    
    context = {
        "mode":get_mode(request),
    }
    if 'username' in request.session:
        username = request.session['username']
        request.session['username'] = None
        context['username'] = username
    else:
        context['username'] = ""

        
    if 'error_msg' in request.session:
        error_msg = request.session['error_msg']
        request.session['error_msg'] = None
        context['error_msg'] = error_msg
    else:
       context['error_msg'] = None 
    
    return render(request, 'base/register.html',context)

def authenticate_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        request.session['error_msg']=None
        login(request, user)
        return redirect('base:profile', user.id)
    else:
        request.session['error_msg']='Username or password is incorrect'
        return redirect('base:login')
    
def detail(request, id):
    message:Message = Message.objects.get(id=id)

    if request.method == 'POST':
        message.body = request.POST['content']
        message.title = request.POST['title']
        message.public = bool(int(request.POST['public']))
        message.save()
    if not message.public and not message.owner == request.user:
        return redirect('base:index')


    context ={
        'message':message,
        "mode":get_mode(request),
    }
    message.views +=1
    message.save()
    return render(request, 'base/detail.html',context)

def create(request):
    message = Message()
    if request.method == 'POST':
        message = Message.objects.create(title=request.POST['title'],
         body=request.POST['content'])
        if request.user.is_authenticated:
            message.owner = request.user
            message.public = bool(int(request.POST['public']))
            message.save()
        request.session['back_url'] = request.META['HTTP_REFERER']
        return redirect('base:detail', message.id)
    context = {
        "mode":get_mode(request),
        'message':message,
        "show_back_button":True,
    }
    return render(request, 'base/create.html',context)

def edit(request,id=1):
    message:Message = Message.objects.get(id=id)
    if message.owner == request.user:
        context ={
            'message':message,
            "show_back_button":True,
            "mode":get_mode(request),
        }
        return render(request, 'base/edit.html',context)
    
def raw(request,id):
    message:Message = Message.objects.get(id=id)
    context ={
        'message':message
    }
    return render(request, 'base/raw.html',context)

def logout_view(request):
    logout(request)
    return redirect('base:index')

def download_view(request, id):
    message:Message = Message.objects.get(id=id)
    file_data = message.body
    filename = slugify(message.title[:50])
    if len(filename)==0:
        filename = 'dowloaded-file'
    response = HttpResponse(file_data, content_type='application/text charset=utf-8')
    response['Content-Disposition'] = f'attachment; filename="{filename}.txt"'
    return response

def search(request):
    recent_messages = Message.objects.filter(public=True).order_by('-created_at')[:10]
    q = request.GET['q']
    
    page = get_page(request)
    messages_raw = Message.objects.filter((Q(owner__username__icontains=q) | Q(title__icontains=q)) & Q(public=True))
    messages_count = messages_raw.count()
    messages = messages_raw[(page-1)*10:(page)*10]



    page_max = get_page_max(messages_count)
    

    show_page_selector = not((page-1 == 0) and (page_max == page)) 
    context = {
        "recent_messages":recent_messages,
        "messages":messages,
        "page_prev":page-1,
        "page_next":page+1,
        "page_max":page_max,
        "page":page,
        "show_page_selector":show_page_selector,
        "q":q,
        "mode":get_mode(request),
    }
    return render(request, 'base/search.html', context)

def delete(request, id):
    message = Message.objects.get(id=id)
    if not request.user == message.owner:
        return redirect('base:detail', message.id)

    if request.method == 'POST':
        deletion_bool:bool= True if request.POST['delete'] =="Yes" else False;
        if deletion_bool:
            message.delete()
            return redirect('base:profile', request.user.id)
        else:
            return redirect('base:detail', message.id)



    context = {
        'message':message,
        "mode":get_mode(request),
    }
    return render(request, 'base/delete.html',context)

def change_mode(request):
    if not 'mode' in request.session or request.session['mode'] == 'light':
        request.session['mode'] = 'dark'
    else:
        request.session['mode'] = 'light'
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def back(request):
    if 'back_url' in request.session:
        return HttpResponseRedirect(request.session.pop('back_url'))
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

base/templates/base/delete.html
{% extends 'base/page-layout-prompt.html' %}
{% load static %}
{% block name %}
    Deletion
{% endblock %}

{% block prompt_contents %}
<form class="login-form" method="post" action="" >
    {% csrf_token %} 
    <p class="message-deletion-info">Do you want to delete the message with title: "{{message.title}}"?</p>
    
    <div class="buttons-deletion-wrapper">
        <input class="button" type="submit" value="No" name="delete">
        <input class="button" type="submit" value="Yes" name="delete">
    </div>
    
</form>
{% endblock %}

base/templates/base/detail.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}
    <div class="message-editor-wrapper">
        <div class="message-status-bar">
            <a href="{% url 'base:back' %}">
                <button class="button">Back</button>
            </a>
            
            <div class="message-right-header">
                {% if message.owner == request.user %}
                <a href="{% url 'base:edit' message.id %}"><button class="button">Edit</button></a>
                {% endif %}
                <a href="{% url 'base:raw' message.id %}"><button class="button">Raw</button></a>
                <a href="{% url 'base:download' message.id %}"><button class="button">Download</button></a>
            </div>
        </div>
        <div class="message-status-bar-lower">
            <div class="left-detail-div">
                    {% if message.owner %}
                <a class="author-link" href="{% url 'base:profile' message.owner.id %}"><p class="space-container-head-info-author">{{ message.owner.username }}</p></a>
                {% else %}
                <p class="space-container-head-info-author">No author</p>
                {% endif %}
                <p class="space-container-head-info-author">Views: {{message.views}}</p>
                {% if message.owner == request.user %}
                    {% if message.public %}
                        <p class="space-container-head-info-author">Public</p>
                    {% else %}
                        <p class="space-container-head-info-author">Private</p>
                    {% endif %}
                
                
                {% endif %}
            </div>
            <div class="right-detail-div">
                {% if message.owner == request.user %}
                <a href="{% url 'base:delete' message.id %}"><button class="button">Delete</button></a>
                {% endif %}
            </div>
            
         
        </div>
        <div class="message-title-bar">
            {{message.title}}
        </div>
        <div class="message-content">
            <pre>{{message.body}}</pre>
        </div>
    </div>
{% endblock %}

base/templates/base/edit.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}
    <div class="message-editor-wrapper">
        <div class="message-editor-label">
            <p>Editing your Space</p>
        </div>
        <form method="post" action="{% url 'base:detail' message.id %}" class="message-form">
            {% include 'base/editor-container.html' %}
        </form>
        
    </div>
{% endblock %}

base/templates/base/editor-container.html
{% csrf_token %}
<div class="message-status-bar">

    {% if show_back_button %}
    <button class="button" type="button" onclick="javascript:history.go(-1)">Back</button>
    {% else %}
    <button class="button" type="button" onclick="{% url 'base:back' %}" style="visibility: hidden;">Back</button>
    {% endif %}
    
    <div class="editor-status-bar">
        <button class="button" type="submit">Save</button>
    </div>
</div>
<div class="editor-title-bar">
    <textarea name="title" class="title-input" rows="3" placeholder="Title" required="required">{{message.title}}</textarea>
    {% if request.user.is_authenticated %}
        <select name="public" class="public-selector">
            <option value="1" {% if message.public %} selected="selected"{% endif %} >Public</option>
            <option value="0" {% if not message.public %}selected="selected"{% endif %} >Private</option>
        </select>
    {% endif %}
</div>
<div class="editor-content">
    <textarea name="content" required="required" class="title-input" rows="44" placeholder="Content goes here...">{{message.body}}</textarea>
</div>

base/templates/base/index.html
{% extends "base/main.html" %}
{% load static %}
{% block content %}
    <div class="content-wrapper">
        <div class="main-content">
            {% include 'base/welcome-container.html' %}
            <!-- <div class="larger">
                {% include 'base/space-container-add.html' %}
            </div> -->
            <form method="post" action="{% url 'base:create' %}"> 
                <div class="message-editor-wrapper smaller">
                    {% include 'base/editor-container.html' %}
                </div> 
            </form>
                
            
            

            <div class="extended-index">
                <div class="section-name">
                    <p>
                        Recent activity
                    </p>
                </div>
                <div class="section-content">
                    {% for message in recent_messages %}
                        {% include 'base/space-container.html' %}
                    {% endfor %}
                </div>
                
            </div>


        </div>
        <div class="recent-activity">
            <div class="section-name">
                <p>
                    Recent activity
                </p>
            </div>
            <div class="section-content">
                {% for message in recent_messages %}
                    {% include 'base/space-container.html' %}
                {% endfor %}
            </div>
            
        </div>
    </div>
{% endblock %}

base/templates/base/login.html
{% extends 'base/page-layout-prompt.html' %}
{% load static %}
{% block name %}
    Login
{% endblock %}

{% block prompt_contents %}
    {% if error_msg %}
    <p class="error-message">{{error_msg}}</p>
    {% endif %}
    <form class="login-form" action="{% url 'base:authenticate' %}" method="post">
        {% csrf_token %}
        <div class="input-label">
            <p class="field-name">Username:</p>
            <input type="text" class="input-field" name="username" required='required'>
        </div> 
        <div class="input-label">
            <p class="field-name">Password:</p>
            <input type="password" class="input-field" name="password" required='required' id="id_password">
            <img src="{% static 'base/eye.png' %}" class id="togglePassword">
        </div> 
        
        
        <input class="button" type="submit" value="Login">
    </form>
    <a href="{% url 'base:register' %}"><p class="not-user">No account yet? Register here</p></a>

{% endblock %}

base/templates/base/main.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width">
        <meta http-equiv = "Content-Type" content = "text/html; charset = UTF-8" />
        <meta name = "description" content = "Openpaste is a website, where you can save any text for unlimited amount of time" />
        <meta name = "keywords" content = "Paste, Pastebin, Copy, Text, Snippets, Code, Save, Secure, Config" />
        <meta name = "author" content = "Daniel Zierl" />
        <title>Openpaste - Free and opensource paste storage!</title>
        <link rel="icon" type="image/x-icon" href="{% static 'base/favicon.png' %}">
        {% if mode == 'light' %}
        <link rel="stylesheet" href="{% static 'base/styles/light-mode.css' %}" type="text/css">
        {% else %}
        <link rel="stylesheet" href="{% static 'base/styles/dark-mode.css' %}" type="text/css">
        {% endif %}

        <link rel="stylesheet" href="{% static 'base/styles/styles.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'base/styles/topbar.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'base/styles/footer.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'base/styles/general-styles.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'base/styles/login.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'base/styles/index.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'base/styles/space-container-add.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'base/styles/welcome-container.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'base/styles/space-container.css' %}" type="text/css">
        <script src="{% static 'base/hamburger.js' %}" defer></script>
        <script src="{% static 'base/shrink_nav_bar.js' %}" defer></script>
        <script src="{% static 'base/show-pass.js' %}" defer></script>
    </head>
    <body>
        
            {% include 'base/topbar.html' %}
            {% block content %}
            {% endblock %}
        
        {% include 'base/footer.html' %}
    </body>
</html>

base/templates/base/page-selector-container.html
<div class="page-selector-wrapper">
    {% if show_page_selector %}
    <form method="get" action="" class="page-selector-form">
        {% if page_prev == 0 %}
            <button class="button greyed" type="submit" value="{{page_prev}}" name="page">Previous page</button>
        {% else %}
            <button class="button" type="submit" value="{{page_prev}}" name="page">Previous page</button>
        {% endif %}
        {% if page_max == page %}
        <button class="button greyed" type="submit" value="{{page_next}}" name="page">Next page</button>
        {% else %}
        <button class="button" type="submit" value="{{page_next}}" name="page">Next page</button>
        {% endif %}
        <input type="text" style="display: none;" value="{{q}}" name="q">
    </form>
    {% endif %}
    
</div>

base/templates/base/profile.html
{% extends 'base/page-layout.html' %}

{% block name %}
{{user.username}}'s spaces
{% endblock %}


{% block section-content %}
    {% if user == request.user %}
        {% include 'base/space-container-add.html' %}
    {% endif %}

    {% for message in messages %}
        {% include 'base/space-container.html' %}
    {% endfor %}

    {% include 'base/page-selector-container.html' %}
{% endblock %}

base/templates/base/raw.html
{% if not message.public and not message.owner == request.user %}
You are not authorized to see the message
{% else %}
{{ message.body }}
{% endif %}

base/templates/base/search.html
{% extends 'base/page-layout.html' %}

{% block name %}
<p>Search results</p>
{% endblock %}


{% block section-content %}
    {% for message in messages %}
        {% include 'base/space-container.html' %}
    {% endfor %}
    {% include 'base/page-selector-container.html' %}
{% endblock %}

base/templates/base/space-container-add.html
{% load static %}
<a href="{% url 'base:create' %}" class="a-wrapper">
    <div class="space-container-add-wrapper">
    
        
        <div class="space-container-content">
            <div class="new-space-button-wrapper">
                
                <svg class="new-space" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M24 10h-10v-10h-4v10h-10v4h10v10h4v-10h10z"/></svg>
            </div>
            
        </div>
    
    
    </div>
</a>

base/templates/base/space-container.html
{% load static %}
{% load timesince %}
<div class="space-container-wrapper">
    <a href="{% url 'base:detail'  message.id %}" class="link-wrapper">
    
    <div class="space-container-head">
        <!-- <div class="avatar-container">
            <img src="{% static 'base/avatar.jpg'%}" class="avatar">
        </div> -->
        <div class="space-container-head-higher">
            {% if message.owner %}
                <a href="{% url 'base:profile' message.owner.id %}" class="author-link-wrapper">
                    <p class="space-container-head-info-author">{{ message.owner.username }}</p>
                </a>
            {% else %}
            
            <a href="{% url 'base:index'  %}" class="author-link-wrapper">
                <p class="space-container-head-info-author">No author</p>
            </a>

            {% endif %}
            <div class="filler">
                
            </div>
            <p class="space-container-head-info-date">{{ message.created_at | timesince}} ago</p>
        </div >
            <div class="space-container-head-lower">
                <div class="space-container-title">
                    <p>{{ message.title|slice:":100" }}</p>
                </div>
                
            </div>
            
        </div>
        <div class="space-container-content">
            <p>{{ message.body|slice:":200" }}...
            </p>
        </div>
    
    
    </a>
    </div>

base/templates/base/welcome-container.html
{% load static %}

<div class="welcome-container-wrapper">
    <p class="welcome-message">
        Welcome to Openpaste! A place to share your snippets of text...
    </p>
    <!-- <div class="img-wrapper">
        <img src="{% static 'base/intro_pic.jpg' %}" class="intro-pic">
    </div> -->
    <p>
        
    </p>
</div>